### ISSUE TITLE
UPSLib.vbproj missing

### ISSUE THREAD

**Issue by starsoccer** [Sukasa/UPSLib#1]
It looks like your initial commit did not include the UPSLib project which seems to have most of the interaction with the UPS in it.

**Comment by Sukasa** [comment]
Well that's embarrassing.  I'll see about getting that uploaded tonight

**Comment by Sukasa** [comment]
Okay.  I'm just going to take the easy way out; deleting this repo and recreating it.  I don't know where the original repo is on this computer after some HDD shenanigans, and it's likely the wrong folder/code anyways.
